### ISSUE TITLE
Lines not being drawn in OnDrag Canvas Event systems

### ISSUE THREAD

**Issue by olonge** [geniikw/drawLine#1]
1stly, thanks for sharing this.
I've spent most of today, trying to get this to work.

The current setup works when points are added to the uilineMesh before playing the game, but modifications to the uiline.points during game-play do not show up in the game.
 however, if you end play, and make any change at all, e.g. clicking the RayCast target, then the transforms show up in the editor and the lines show up in the game.

This would have been perfect for me as I need to draw some Bezier lines in game

**Comment by velddev** [comment]
Make sure you call `UIMeshLine.OnRebuildRequested();` when you change it's transformation.

**Comment by olonge** [comment]
many thanks for the response

**Comment by geniikw** [comment]
Fixed it. but I think it is bad solution :(

**Comment by ocaio** [comment]
On the same topic, what's the right way to add points to the line at runtime? 
I'm trying without success to create a new LinePoint object, set its 'Vector2 point' variable and then adding it to UIMeshLine 'points' list. When I try to debug it via inspector, all the points have the same coordinates and I cannot manually change them. Any thoughts?

And of course, many thanks for the great work on this project!

**Comment by geniikw** [comment]
fix... and add a scene that example of add point. please check.

**Comment by ocaio** [comment]
Thanks a lot, geniikw! It worked perfectly :)
